### ISSUE TITLE
Error when uploading a photo

### ISSUE THREAD

**Issue by itfdw** [webianks/EasyFeedback#1]
ring result ResultInfo{who=null, request=125, result=-1, data=Intent { dat=content://media/external/images/media/14822 (has extras) }} to activity {com.webianks.easyfeedback/com.webianks.easy_feedback.FeedbackActivity}: java.lang.ArithmeticException: divide by zero

**Comment by itfdw** [comment]
I think the problem happens when you take a vertical image , it does not put in landscape

**Comment by webianks** [comment]
Okay I will check and try to fix this.

**Comment by webianks** [comment]
Hey sorry for delayed response. I tried with different images but there was no such issue. Can you provide the image which you are trying  to upload ?
