### ISSUE TITLE
Crash with - "You need to use a Theme.AppCompat theme (or descendant) with this activity."

### ISSUE THREAD

**Issue by ebernie** [webianks/EasyFeedback#3]
Followed the code from the site but FeedbackActivity will not launch. It crashes with the above message.

**Comment by webianks** [comment]
Because you must be using material or holo theme in your app and also you must be extending all your activities to 'Activity' but this FeedbackActivity extends AppCommpatActivity so you should use 'Theme.AppCompat...'  in your app theme. Google this you will know.

**Comment by ebernie** [comment]
I am already extending AppCompatActivity, and my app theme inherits from Theme.AppCompat.

The workaround I'm using right now is to
1. Extend FeedbackActivity with my own Activity
2. Have the sub-class of FeedbackActivity declared in AndroidManifest, using my AppTheme (again, its parent is Theme.AppCompat)
3. Launch the sub-class manually using Intent

Side note: when I started using this library it was working, but something triggered this. Maybe Android support library upgrade, but I can't confirm this. Just FYI.

**Comment by webianks** [comment]
Have you figured out the problem ? Can you post your gradle configs here.
